name: CI/CD - DexScreener Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Image
      run: docker build -t backend-test ./backend

    - name: Build Frontend Image
      run: docker build -t frontend-test ./frontend

    - name: Compose Up Test (No Deploy)
      run: docker-compose -f docker-compose.yml up -d --build